### ISSUE TITLE
TypeError: cli is not a function

### ISSUE THREAD

**Issue by japsu** [ekmartin/slack-irc#165]
Release 3.8.6 seems to be broken.

```
myrmidon:ansible-tracon japsu$ npm install --global slack-irc
myrmidon:ansible-tracon japsu$ slack-irc
/usr/local/lib/node_modules/slack-irc/dist/index.js:29
  cli();
  ^

TypeError: cli is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/slack-irc/dist/index.js:29:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
myrmidon:ansible-tracon japsu$ npm list --global |grep slack-irc
└─┬ slack-irc@3.8.6
```

**Comment by ekmartin** [comment]
Wow, that's awkward! Thanks for letting me know. I broke it when I "fixed" the API in https://github.com/ekmartin/slack-irc/pull/163#issuecomment-250000061. Should be good to go again in version 3.8.7.
